services: # Ejemplo de Uso de 3 Contenedores con Docker Composer, Para Levantar Este Fichero de Configuración Usa: docker compose up -d
# Instalo MySQL
  db:
    # Se Puede Usar MariaDB si Descomentas la Siguiente Línea
    # image: mariadb:10.6.4-focal
    # Si Usas MariaDB Por Favor Comenta la Siguiete Línea de MySQL.
    image: mysql:8.0.27 # Uso MySQL Como Sistema Gestor de Base de Datos.
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
    networks:
      - mysql-phpmyadmin

# Instalo Wordpress
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always

# Instalo phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
