// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Practica_Api_Examen.Models;

namespace Practica_Api_Examen.Data;

public partial class BibliotecaContext : DbContext
{
    public BibliotecaContext(DbContextOptions<BibliotecaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Autor> autor { get; set; }

    public virtual DbSet<Estudiante> estudiante { get; set; }

    public virtual DbSet<Libro> libro { get; set; }

    public virtual DbSet<Prestamo> prestamo { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Autor>(entity =>
        {
            entity.HasKey(e => e.Id_Autor).HasName("PK__autor__0DC8163EA68C4E87");

            entity.Property(e => e.Edad)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength();
            entity.Property(e => e.Nacionalidad).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Nombre).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Estudiante>(entity =>
        {
            entity.HasKey(e => e.Id_Lector).HasName("PK__estudian__7B5F87A1345A2C8D");

            entity.Property(e => e.Apellido).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.CI)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength();
            entity.Property(e => e.Carrera).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Direccion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Edad)
                .HasDefaultValueSql("(NULL)")
                .IsFixedLength();
            entity.Property(e => e.Nombre).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Libro>(entity =>
        {
            entity.HasKey(e => e.Id_Libro).HasName("PK__libro__FFFE46402CB11101");

            entity.Property(e => e.Area).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Editorial).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Titulo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.fechacompra).HasDefaultValueSql("(NULL)");
        });

        modelBuilder.Entity<Prestamo>(entity =>
        {
            entity.Property(e => e.Devuelto).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Fecha_Devuelto).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Fecha_Prestamo).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Id_Lector).HasDefaultValueSql("(NULL)");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}