// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PO02_01.Models;

[Table("Genre")]
public partial class Genre
{
    [Key]
    public int GenreID { get; set; }

    [DisplayName("Género")]
    [Required(ErrorMessage = "Campo obligatorio.")]
    [StringLength(80, ErrorMessage = "Este campo debe tener entre menos de {1} caracteres.")]
    public string GenreName { get; set; }

    [DisplayName("Series del género")]
    [InverseProperty("Genre")]
    public virtual ICollection<Serie> Series { get; set; } = new List<Serie>();
}