// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PO02_01.Models;

public partial class Serie
{
    [Key]
    public int SeriesID { get; set; }

    [DisplayName("Serie")]
    [Required(ErrorMessage = "Campo obligatorio.")]
    [StringLength(100, ErrorMessage = "Este campo debe tener entre menos de {1} caracteres.")]
    public string SeriesName { get; set; }

    [DisplayName("Fecha de publicación")]
    [Required(ErrorMessage = "Campo obligatorio.")] // ? es obligatorio?
    public DateOnly? ReleaseDate { get; set; }

    [DisplayName("Descripción")]
    [Required(ErrorMessage = "Campo obligatorio.")]
    [StringLength(400, ErrorMessage = "Este campo debe tener entre menos de {1} caracteres.")]
    public string Description { get; set; }

    public int? GenreID { get; set; }

    [ForeignKey("GenreID")]
    [InverseProperty("Series")]
    [DisplayName("Género")]
    public virtual Genre Genre { get; set; }

    [DisplayName("Recomendaciones")]
    public List<Recommendation> Recommendations { get; set; }
}