// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PO03_01.Data;

#nullable disable

namespace PO03_01.Migrations
{
    [DbContext(typeof(GameStoreAPIContext))]
    partial class GameStoreAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PO03_01.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenreId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK__Game__3214EC0752266EFA");

                    b.HasIndex("GenreId");

                    b.ToTable("Game", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PO03_01.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Genre__3214EC07385AD64A");

                    b.ToTable("Genre", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PO03_01.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ComercialId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Pedido");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Wallaby 42, Sidney",
                            Amount = 5,
                            ComercialId = "",
                            GameId = 18
                        },
                        new
                        {
                            Id = 2,
                            Address = "742 Evergreen Terrace, Springfield",
                            Amount = 8,
                            ComercialId = "",
                            GameId = 6
                        },
                        new
                        {
                            Id = 3,
                            Address = "221B Baker Street, London",
                            Amount = 2,
                            ComercialId = "",
                            GameId = 7
                        });
                });

            modelBuilder.Entity("PO03_01.Models.Game", b =>
                {
                    b.HasOne("PO03_01.Models.Genre", "Genre")
                        .WithMany("Game")
                        .HasForeignKey("GenreId")
                        .HasConstraintName("FK__Game__GenreId__286302EC");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("PO03_01.Models.Pedido", b =>
                {
                    b.HasOne("PO03_01.Models.Game", "Game")
                        .WithMany("Pedidos")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PO03_01.Models.Game", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("PO03_01.Models.Genre", b =>
                {
                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
