// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AUT03_01_Jardineria.Models;

[Table("gama_producto")]
public partial class gama_producto
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string gama { get; set; }

    [Unicode(false)]
    public string descripcion_texto { get; set; }

    [Unicode(false)]
    public string descripcion_html { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string imagen { get; set; }

    [InverseProperty("gamaNavigation")]
    public virtual ICollection<Producto> productos { get; set; } = new List<Producto>();
}