// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace AUT03_01_Jardineria.Models;

[Table("producto")]
public partial class Producto
{
    [Key]
    public int codigo_producto { get; set; }

    [Required]
    [StringLength(70)]
    [Unicode(false)]
    public string nombre { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string gama { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string dimensiones { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string proveedor { get; set; }

    [Unicode(false)]
    public string descripcion { get; set; }

    public short cantidad_en_stock { get; set; }

    [Column(TypeName = "numeric(15, 2)")]
    public decimal precio_venta { get; set; }

    [Column(TypeName = "numeric(15, 2)")]
    public decimal? precio_proveedor { get; set; }

    [ForeignKey("gama")]
    [InverseProperty("productos")]
    public virtual gama_producto gamaNavigation { get; set; }

    public List<Review> reviews { get; set; }
}