// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.EntityFrameworkCore;
using PO03_01.Models;

namespace PO03_01.Data;

public partial class GameStoreAPIContext : DbContext
{
    public GameStoreAPIContext()
    {
    }

    public GameStoreAPIContext(DbContextOptions<GameStoreAPIContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Game> Game { get; set; }

    public virtual DbSet<Genre> Genre { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Game>().ToTable(nameof(Game), t => t.ExcludeFromMigrations());
        modelBuilder.Entity<Genre>().ToTable(nameof(Genre), t => t.ExcludeFromMigrations());

        modelBuilder.Entity<Game>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Game__3214EC0752266EFA");

            entity.HasOne(d => d.Genre).WithMany(p => p.Game).HasConstraintName("FK__Game__GenreId__286302EC");
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Genre__3214EC07385AD64A");
        });

        // REVIEWS SEEDING
        List<Pedido> pedidos = new List<Pedido>()
        {
            new Pedido()
            {
                Id = 1,
                Amount = 5,
                Address = "Calle Wallaby 42, Sidney",
                GameId = 18,
                ComercialId = ""
            },
            new Pedido()
            {
                Id = 2,
                Amount = 8,
                Address = "742 Evergreen Terrace, Springfield",
                GameId = 6,
                ComercialId = ""
            },
            new Pedido()
            {
                Id = 3,
                Amount = 2,
                Address = "221B Baker Street, London",
                GameId = 7,
                ComercialId = ""
            }
        };
        modelBuilder.Entity<Pedido>().HasData(pedidos);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

public DbSet<PO03_01.Models.Pedido> Pedido { get; set; } = default!;
}