// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Jardineria.Models;
using Microsoft.EntityFrameworkCore;

namespace Jardineria.Data;

public partial class JardineriaContext : DbContext
{
    public JardineriaContext(DbContextOptions<JardineriaContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Gama> gama_producto { get; set; }

    public virtual DbSet<Producto> producto { get; set; }

    public DbSet<Review> Review { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Gama>().ToTable("gama_producto", t => t.ExcludeFromMigrations()); // Excluye la Tabla Gama.
        modelBuilder.Entity<Producto>().ToTable("producto", t => t.ExcludeFromMigrations()); // Excluye la Tabla Producto.

        modelBuilder.Entity<Gama>(entity =>
        {
            entity.HasKey(e => e.gama).HasName("PK__gama_pro__4877EEE41EE6C88C");
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.codigo_producto).HasName("PK__producto__105107A9A5787D2D");

            entity.Property(e => e.precio_proveedor).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.proveedor).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.gamaNavigation).WithMany(p => p.producto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__producto__gama__3D5E1FD2");
        });

        modelBuilder.Entity<Review>().HasData
        (
            new Review
            {
                Id = 1,
                Title = "Buena Máquina",
                Description = "La Cadena Corta Muy Bien y es Muy Silenciosa.",
                Stars = 5,
                ProductId = 1
                
            },
            new Review
            {
                Id = 2,
                Title = "Problemas",
                Description = "Se me sale La Cadena, seré yo?.",
                Stars = 3,
                ProductId = 1

            },
            new Review
            {
                Id = 3,
                Title = "Me Gusta",
                Description = "Yo la Uso Para Quitarme los Callos.",
                Stars = 4,
                ProductId = 1

            },
            new Review
            {
                Id = 4,
                Title = "Buen Árbol",
                Description = "Hermoso Arce.",
                Stars = 4,
                ProductId = 179
            },
            new Review
            {
                Id = 5,
                Title = "Que Hojas!",
                Description = "Me Encanta el Arce, un Árbol Hermoso.",
                Stars = 5,
                ProductId = 179
            },
            new Review
            {
                Id = 6,
                Title = "Bonsai?",
                Description = "Es Pequeño, espero que no crezca mucho.",
                Stars = 4,
                ProductId = 179
            }
        );

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}