FROM ngnix:1.26.2-alpine3.20
VOLUME ["/usr/share/nginx/html"]
EXPOSE 80
CMD ["nginx","-g","daemon off;"]

Para Remover todos los Contenedores:

docker rm -v -f $(docker ps -qa)

Muestra los Contenedores en Ejecución:

docker ps

Muestra Todos los Contenedores:

docker ps -a


Para Arrancar(Levantar) Contenedores con Compose:

docker compose up -d


Para Navegar dentro de un contenedor:

docker exec barbery-new-barbery-1 ls /etc/nginx

Muestra el contenido del directorio /etc/nginx.


Muestra el Contenido del Fichero nginx.conf (docker comando a ejecutar(exec) nombre del contenedor(barbery-new-barbery-1) Comando a Ejecutar Dentro del Contenedor(cat) Ruta al Fichero(/etc/nginx/nginx.conf):

docker exec barbery-new-barbery-1 cat /etc/nginx/nginx.conf


Para Pasaar un Dump SQL a MariaDB o MySQL Server:

entrypoint: "mysql -h db -u root --password=Contr@senia -D barbery -e 'source /barbery.sql'"

entrypoint: "mysql -h $DB_HOST -u $DB_USERNAME --password=$DB_PASSWORD -D $DB_DATABASE -e 'source /barbery.sql'"