// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using AUT03_01_Jardineria.Models;
using AUT03_01_Jardineria.Models.Auth;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AUT03_01_Jardineria.Data;

public class LeslieContext : IdentityDbContext<JardinUser>
{
    public LeslieContext()
    {
    }

    public LeslieContext(DbContextOptions<LeslieContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // USERS SEEDING
        List<JardinUser> users = new List<JardinUser>()
        {
            new JardinUser()
            {
                UserName = "basic@jardin.com",
                NormalizedUserName = "BASIC@JARDIN.COM",
                Email = "basic@jardin.com",
                NormalizedEmail = "BASIC@JARDIN.COM",
                FullName = "Usuario Basic",
                Address = "Calle Wallaby 42, Sidney",
                Phone = "666777888",
                PostalCode = "55555"
            },
            new JardinUser()
            {
                UserName = "premium@jardin.com",
                NormalizedUserName = "PREMIUM@JARDIN.COM",
                Email = "premium@jardin.com",
                NormalizedEmail = "PREMIUM@JARDIN.COM",
                FullName = "Usuario Premium",
                Address = "742 Evergreen Terrace, Springfield",
                Phone = "666555444",
                PostalCode = "77777"
            },
            new JardinUser()
            {
                UserName = "admin@jardin.com",
                NormalizedUserName = "ADMIN@JARDIN.COM",
                Email = "admin@jardin.com",
                NormalizedEmail = "ADMIN@JARDIN.COM",
                FullName = "Usuario Admin",
                Address = "221B Baker Street, London",
                Phone = "654987321",
                PostalCode = "88888"
            }
        };
        modelBuilder.Entity<JardinUser>().HasData(users);
        // PASSWORD HASH
        var passwordHasher = new PasswordHasher<JardinUser>();
        foreach(var user in users)
        {
            user.PasswordHash = passwordHasher.HashPassword(user, "Asdf1234!");
        }

        // ROLES SEEDING
        List<IdentityRole> roles = new List<IdentityRole>()
        {
            new IdentityRole()
            {
                Name = "Basic",
                NormalizedName = "BASIC"
            },
            new IdentityRole()
            {
                Name = "Premium",
                NormalizedName = "PREMIUM"
            },
            new IdentityRole()
            {
                Name = "Admin",
                NormalizedName = "ADMIN"
            }
        };
        modelBuilder.Entity<IdentityRole>().HasData(roles);

        // USERS-ROLES SEEDING
        List<IdentityUserRole<string>> usersRoles = new List<IdentityUserRole<string>>()
        {
            new IdentityUserRole<string>()
            {
                UserId = users[0].Id,
                RoleId = roles[0].Id
            },
            new IdentityUserRole<string>()
            {
                UserId = users[1].Id,
                RoleId = roles[1].Id
            },
            new IdentityUserRole<string>()
            {
                UserId = users[2].Id,
                RoleId = roles[2].Id
            }
        };
        modelBuilder.Entity<IdentityUserRole<string>>().HasData(usersRoles);
    }
}