// <auto-generated />
using System;
using AUT03_01_Jardineria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AUT03_01_Jardineria.Migrations.Jardineria
{
    [DbContext(typeof(JardineriaContext))]
    [Migration("20241212095623_ReviewsMigration")]
    partial class ReviewsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AUT03_01_Jardineria.Models.Producto", b =>
                {
                    b.Property<int>("codigo_producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo_producto"));

                    b.Property<short>("cantidad_en_stock")
                        .HasColumnType("smallint");

                    b.Property<string>("descripcion")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("dimensiones")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("gama")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)");

                    b.Property<decimal?>("precio_proveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(15, 2)")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<decimal>("precio_venta")
                        .HasColumnType("numeric(15, 2)");

                    b.Property<string>("proveedor")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("codigo_producto")
                        .HasName("PK__producto__105107A934D97F41");

                    b.HasIndex("gama");

                    b.ToTable("Producto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "Sirve",
                            ProductId = 1,
                            Stars = 4,
                            Title = "Está ok"
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "Me hice pupa",
                            ProductId = 1,
                            Stars = 3,
                            Title = "Regulero"
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "Super divino de la muerte",
                            ProductId = 1,
                            Stars = 5,
                            Title = "Maravilloso"
                        },
                        new
                        {
                            ReviewId = 4,
                            Description = "Ta chiquita",
                            ProductId = 179,
                            Stars = 2,
                            Title = "Pequeña"
                        },
                        new
                        {
                            ReviewId = 5,
                            Description = "Justo lo que necesitaba",
                            ProductId = 179,
                            Stars = 5,
                            Title = "Perfecto"
                        },
                        new
                        {
                            ReviewId = 6,
                            Description = "Encajan perfectamente en mi jardín",
                            ProductId = 179,
                            Stars = 5,
                            Title = "Preciosas"
                        });
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.gama_producto", b =>
                {
                    b.Property<string>("gama")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("descripcion_html")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("descripcion_texto")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("imagen")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("gama")
                        .HasName("PK__gama_pro__4877EEE4998666B4");

                    b.ToTable("gama_producto", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.Producto", b =>
                {
                    b.HasOne("AUT03_01_Jardineria.Models.gama_producto", "gamaNavigation")
                        .WithMany("productos")
                        .HasForeignKey("gama")
                        .IsRequired()
                        .HasConstraintName("FK__producto__gama__3D5E1FD2");

                    b.Navigation("gamaNavigation");
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.Review", b =>
                {
                    b.HasOne("AUT03_01_Jardineria.Models.Producto", "Producto")
                        .WithMany("reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.Producto", b =>
                {
                    b.Navigation("reviews");
                });

            modelBuilder.Entity("AUT03_01_Jardineria.Models.gama_producto", b =>
                {
                    b.Navigation("productos");
                });
#pragma warning restore 612, 618
        }
    }
}
