// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Practica_Api_Examen.Models;

public partial class Estudiante
{
    [Key]
    [Column(TypeName = "decimal(10, 0)")]
    public decimal Id_Lector { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string CI { get; set; }

    [Column(TypeName = "text")]
    public string Nombre { get; set; }

    [Column(TypeName = "text")]
    public string Apellido { get; set; }

    [Column(TypeName = "text")]
    public string Direccion { get; set; }

    [Column(TypeName = "text")]
    public string Carrera { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string Edad { get; set; }
}