// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Practica_Api_Examen.Models;

public partial class Libro
{
    [Key]
    [Column(TypeName = "decimal(10, 0)")]
    public decimal Id_Libro { get; set; }

    [Column(TypeName = "text")]
    public string Titulo { get; set; }

    [Column(TypeName = "text")]
    public string Editorial { get; set; }

    [Column(TypeName = "text")]
    public string Area { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fechacompra { get; set; }
}