// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PO03_01.Models;

public partial class Game
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    public string Title { get; set; }

    public string Description { get; set; }

    public int? Stock { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? Price { get; set; }

    public int? GenreId { get; set; }

    [ForeignKey("GenreId")]
    [InverseProperty("Game")]
    public virtual Genre Genre { get; set; }

    public List<Pedido> Pedidos { get; set; } = new List<Pedido>();
}