apiVersion: v1
kind: Namespace
metadata:
  name: cesar
---
apiVersion: v1

kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: cesar
spec:
  hard:
    pods: "1"
    limits.cpu: "4"
    limits.memory: 2Gi
    requests.cpu: "4"
    requests.memory: 2Gi

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  namespace: cesar
  labels:
    app: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          imagePullPolicy: IfNotPresent
          image: orions68/php
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
    name: php-service
    namespace: cesar
spec:
    selector:
        app: php
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
