// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.ConstrainedExecution;
using DataBaseFirst.Models;
using Microsoft.EntityFrameworkCore;

namespace DataBaseFirst.Data;

public partial class NorthwindContext : DbContext
{
    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Supplier> Suppliers { get; set; }
    public virtual DbSet<Shipper> Shippers { get; set; }
    public DbSet<DataBaseFirst.Models.Company> Company { get; set; } = default!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //modelBuilder.Entity<Supplier>().ToTable("Suppliers", t => t.ExcludeFromMigrations()); // Excluye la Tabla Suppliers.
        //modelBuilder.Entity<Shipper>().ToTable("Shippers", t => t.ExcludeFromMigrations()); // Excluye la Tabla Shippers.

        //modelBuilder.Entity<Company>().HasData(
        //        new Company
        //        {
        //            Id = 1,
        //            Name = "Microsoft",
        //            Description = "El otro Gigante Azul",
        //            ShipperId = 1
        //        },
        //        new Company
        //        {
        //            Id = 2,
        //            Name = "Google",
        //            Description = "Corvette",
        //            ShipperId = 2
        //        },
        //        new Company
        //        {
        //            Id = 3,
        //            Name = "Apple",
        //            Description = "No soy Fan de Ellos",
        //            ShipperId = 3
        //        }
        //    );

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}