// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.ConstrainedExecution;
using DataBaseFirst.Models;
using Microsoft.EntityFrameworkCore;

namespace DataBaseFirst.Data;

public partial class NorthwindContext : DbContext
{
    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Supplier> Suppliers { get; set; }
    public virtual DbSet<Shipper> Shippers { get; set; }
    //public DbSet<DataBaseFirst.Models.Company> Company { get; set; } = default!;

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //modelBuilder.Entity<Supplier>().ToTable("Supplier", t => t.ExcludeFromMigrations()); // Excluye la Tabla Supplier.
        //modelBuilder.Entity<Shipper>().ToTable("Shipper", t => t.ExcludeFromMigrations()); // Excluye la Tabla Shipper.

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}